# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Flake8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
        restore-keys: ${{ runner.os }}-pip-

    - name: Setup Python 2.7
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Install Dependencies
      id: setup-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Flake8 Lint
      id: flake8
      run: |
        flake8 . --count --show-source --statistics

    - name: build Package
      id: build
      run: |
        tar cvzf build.tar.gz  ./*
        echo ${{ github.ref }}

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     body: |
    #       Changes in this Release
    #       - First Change
    #       - Second Change
    #     draft: false
    #     prerelease: false
