# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Flake8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
        restore-keys: ${{ runner.os }}-pip-

    - name: Setup Python 2.7
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Install dependencies
      id: setup-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Flake8 lint
      id: flake8
      run: |
        git log --max-count=1
        echo
        flake8 . --count --show-source --statistics
